/* Cách make cả bộ ứng dụng */
Chạy D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/Map U_example.bat để set đường dẫn
cd D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/internal/X2x/E2x/modules/fls/workspace/E2xFCC1/4_2_2
./Driver_script.sh   /* Run script */
make config_path     /* Compile */
make list            /* Show the list of projects */
make [name in list]  /* Select one of them and make */


/* Cách build từng project bằng Mintty */
chạy code này trong D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/modules/fls/generator
nhớ sửa đường dẫn trong mấy file .trxml trong D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator

\./Fls_X2x.exe -l -o ./ 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/Test_Application_E2x_aes.trxml      /* CDF file first */
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/FLS_CFG_CfgH_001.arxml              /* COnfig file second */
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/Mcu_Cfg001.arxml                    /* MCU Driver */
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/R422_FLS_E2XFCC1_BSWMDT.arxml       /* Basic software */

File include :
-MCU Driver                                          Mcu_Cfg001.arxml 
-BSWMDT Basic software Module Description Template   R422_FLS_E2XFCC1_BSWMDT.arxml  
-FLS Driver component                                FLS_CFG_CfgH_001.arxml

•   ECU Configuration Description File (.arxml)
This file will contain ADC Driver specific configuration information. This file should be generated by
AUTOSAR specified Configuration Editor. 

•   BSWMDT File: ADC Driver Generation
Tool uses “Common Published Information” from ADC module specific BSWMDT File.
ADC module specific BSWMDT File should not be updated manually since it is
“Static Configuration” file. 

•   Translation XML File (.trxml)
This file will contain the path of translation header file and device header file for
particular device (microcontroller). Translation header file will contain the
mapping of register names while device header file will contain register names
and associated address. Based upon the configuration in ECU Configuration
Description File (.arxml) and by using Translation XML, ADC Generation Tool
fetches the addresses from device header file via translation header file. 

•   Configuration XML File (.cfgxml) 
This file will contain the setting of command line options. This file should be located in the same location where
ADC Generation Tool is present. This file is optional file and ADC Generation
Tool will use this file only if command line argument contains only ADC
Generation Tool.

/*-------------------------Source code------------------------------*/
D:/SVN/01_MCALTraining/01_MCAL/01_Training Material/03_Csharp_GENTOOL/Source Code/vNextGentool2/Fls

Copy Fls_X2x.cfgxml vào folder D:/SVN/01_MCALTraining/01_MCAL/01_Training Material/03_Csharp_GENTOOL/Source Code/vNextGentool2/Fls/Fls_X2x/bin/Debug

Dán đoạn sau vào command line argument
\-l -o ./ 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/Test_Application_E2x_aes.trxml 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/FLS_CFG_CfgH_001.arxml 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/Mcu_Cfg001.arxml 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/R422_FLS_E2XFCC1_BSWMDT.arxml  
