/* Cách make cả bộ ứng dụng */
Chạy D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/Map U_example.bat để set đường dẫn
cd D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/internal/X2x/E2x/modules/fls/workspace/E2xFCC1/4_2_2
./Driver_script.sh   /* Run script */
make config_path     /* Compile */
make list            /* Show the list of projects */
make [name in list]  /* Select one of them and make */


/* Cách build từng project bằng Mintty */
chạy code này trong D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/modules/fls/generator
nhớ sửa đường dẫn trong mấy file .trxml trong D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator

\./Fls_X2x.exe -l -o ./ 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/Test_Application_E2x_aes.trxml      /* CDF file first */
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/FLS_CFG_CfgH_001.arxml              /* COnfig file second */
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/Mcu_Cfg001.arxml                    /* MCU Driver */
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/R422_FLS_E2XFCC1_BSWMDT.arxml       /* Basic software */

File include :
-MCU Driver                                          Mcu_Cfg001.arxml 
-BSWMDT Basic software Module Description Template   R422_FLS_E2XFCC1_BSWMDT.arxml  
-FLS Driver component                                FLS_CFG_CfgH_001.arxml

•   ECU Configuration Description File (.arxml)
This file will contain ADC Driver specific configuration information. This file should be generated by
AUTOSAR specified Configuration Editor. 

•   BSWMDT File: ADC Driver Generation
Tool uses “Common Published Information” from ADC module specific BSWMDT File.
ADC module specific BSWMDT File should not be updated manually since it is
“Static Configuration” file. 

•   Translation XML File (.trxml)
This file will contain the path of translation header file and device header file for
particular device (microcontroller). Translation header file will contain the
mapping of register names while device header file will contain register names
and associated address. Based upon the configuration in ECU Configuration
Description File (.arxml) and by using Translation XML, ADC Generation Tool
fetches the addresses from device header file via translation header file. 

•   Configuration XML File (.cfgxml) 
This file will contain the setting of command line options. This file should be located in the same location where
ADC Generation Tool is present. This file is optional file and ADC Generation
Tool will use this file only if command line argument contains only ADC
Generation Tool.

/*-------------------------Source code------------------------------*/
D:/SVN/01_MCALTraining/01_MCAL/01_Training Material/03_Csharp_GENTOOL/Source Code/vNextGentool2/Fls

Copy Fls_X2x.cfgxml vào folder D:/SVN/01_MCALTraining/01_MCAL/01_Training Material/03_Csharp_GENTOOL/Source Code/vNextGentool2/Fls/Fls_X2x/bin/Debug

Dán đoạn sau vào command line argument
\-l -o ./ 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/Test_Application_E2x_aes.trxml 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/FLS_CFG_CfgH_001.arxml 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/Mcu_Cfg001.arxml 
\D:/SVN/01_MCALTraining/01_MCAL/09_mcal_e2x_dev/external/X2x/E2x/common_family/generator/R422_FLS_E2XFCC1_BSWMDT.arxml  


/*-------------------Documents------------------------*/
D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\common\modules\fls\docs\sds


/*--------------Sau khi build bằng Davici, nhớ thêm đoạn code này vào dòng 124---------*/
			  <REFERENCE-VALUES>		
                <ECUC-REFERENCE-VALUE>		
                  <DEFINITION-REF DEST="ECUC-REFERENCE-DEF">/Renesas/EcucDefs_Fls/Fls/FlsGeneral/FlsCpuFrequency</DEFINITION-REF>		
                  <VALUE-REF DEST="ECUC-CONTAINER-VALUE">/ActiveEcuC/Mcu/McuModuleConfiguration/McuClockSettingConfig</VALUE-REF>		
                </ECUC-REFERENCE-VALUE>		
              </REFERENCE-VALUES>


/*---------------------------Cách test******************************-*/
Vào D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\fls
Copy file .c và .h vào trong D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\fls\workspace_cs\E2xFCC1\4_2_2\EvalEnvelope + Test case
Chạy ./testCS.sh <testcase>


"D:\SVN\01_MCALTraining\01_MCAL\01_Training Material\03_Csharp_GENTOOL\X2x\modules\spi\generator_cs"
"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\fls\reqtify\E2xFCC1\Inputs\06_Generation_Test"
"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\spi\workspace\E2xFCC1\4_2_2\EvalEnvelope\Spi_CFGH001_E2xFCC1\cdf"
"D:\SVN\01_MCALTraining\01_MCAL\01_Training Material\03_Csharp_GENTOOL\X2x\modules\spi\generator_cs\SpiX2x\bin\Debug"


/*----------------------------Bài tập SPI-------------------------------*/
- Đầu tiên là make file tạo môi trường.
Bước 1: Chạy Mintty.exe, cd "D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\spi\workspace\E2xFCC1\4_2_2"
Bước 2: ./Config_script.sh  >>  make config_path  >>  make <tên test_case>
Bước 3: Kiểm tra xem trong thư mục <tên test_case>/cdf đã có đủ file chưa. Danh sách file bao gồm:
		- Dem_Spi.arxml
		- R422_spi_E2x_BSWMDT.arxml
		- Spi_CFG_Chk_001.arxml
		- Spi_Mcu.arxml
		- Test_Application_E2x_aes.trxml
- Tiếp theo chạy Gentool spi
		- Mở project C-Sharp tại "D:\SVN\01_MCALTraining\01_MCAL\01_Training Material\03_Csharp_GENTOOL\X2x\modules\spi\generator_cs\SpiX2x\bin\Debug\SpiX2x.exe"
		- Chuột phải vào SpiX2x > Properties. Dán đoạn mã sau vào Debug > Command line argument: 
		"-o ./ cdf/Test_Application_E2x_aes.trxml cdf/Dem_Spi.arxml cdf/R422_SPI_E2x_BSWMDT.arxml cdf/Spi_CFG_Chk_004_5.arxml cdf/Spi_Mcu.arxml"
		- Build, ta có file .c và .h trong thư mục
		"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\spi\workspace\E2xFCC1\4_2_2\EvalEnvelope"
- Cuối cùng compare code tạo ra từ C-Sharp và Perl
		- Copy file testCS.sh vào thư mục "D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\spi"
		- Chạy ./testCS.sh <tên test_case>




/*>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Chỉnh sửa PDF, CDF và C-Sharp>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>*/
Bước 1: Xuất tên API ra header:
		- Vào SpiE2xFCC1CfgFileGeneration.cs, thêm đoạn code. SectionOrder là vị trí sẽ xuất hiện trong file header

		[ItemGeneration(Section = ItemGenerationAttribute.SectionName.GLOBAL_SYMBOLS, SectionOrder = 36)]       /* <<<<<<<<<<<<<<<<<<<< NEW_ >>>>>>>>>>>>>>>>>>*/
        protected virtual BaseGenerationItem SPI_MAX_HSPI_CHANNEL_BUFFER_SIZE_API()
        {
            return CreateBasicParam("SPI_MAX_HSPI_CHANNEL_BUFFER_SIZE_API", Resources.SPI_MAX_HSPI_CHANNEL_BUFFER_SIZE_COMMENT);
        }

        - Trong Resources.Designer.cs thêm code định nghĩa cho Resources.API

        internal static string SPI_SELF_TEST_API_COMMENT {
            get {
                return ResourceManager.GetString("SPI_SELF_TEST_API_COMMENT", resourceCulture);
            }
        }

        - Định nghĩa API trong Resources.resx

        <data name="SPI_MAX_HSPI_CHANNEL_BUFFER_SIZE_COMMENT" xml:space="preserve">
		  <value>/* test 3 */</value>
		</data>

Bước 2: Thêm function trong SpiE2xFCC1Intermediate.cs

		[IntermediateItem(DBPath = "/SPI_SUPPORT_CONCURRENT_ASYNC_TRANSMIT")] 						/* <<<<<< NEW_API >>>>>>>>> */
        protected virtual BaseIntermediateItem Compute_SPI_SUPPORT_CONCURRENT_ASYNC_TRANSMIT()
        {
            string value = string.Empty;

            value = GetParsedStdOnOffBooleanValue(ParseParameterValue(SpiMap.SpiSupportConcurrentAsyncTransmit));
            BaseIntermediateItem ret = new BaseIntermediateItem("SPI_SUPPORT_CONCURRENT_ASYNC_TRANSMIT", value);
            return ret;
        }

/* Đường dẫn */
"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\spi"                                                  << Chạy test diff ở đây >>
"D:\SVN\01_MCALTraining\01_MCAL\01_Training Material\03_Csharp_GENTOOL\Source Code\vNextGentool2\spi"

"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\fls"                                                  << Chạy test diff ở đây >>
"D:\SVN\01_MCALTraining\01_MCAL\01_Training Material\03_Csharp_GENTOOL\Source Code\vNextGentool2\Fls"

"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\spi\reqtify\E2xFCC1\intermediate"                     << File định nghĩa INFO và ERROR >>

"D:\SVN\01_MCALTraining\01_MCAL\01_Training Material\03_Csharp_GENTOOL\X2x\modules\spi\generator_cs\SpiE2xFCC1\Intermediate"   << Edited file here              >>
"D:\SVN\01_MCALTraining\01_MCAL\01_Training Material\03_Csharp_GENTOOL\X2x\modules\spi\generator_cs\SpiX2x\bin\Debug"          << Project và file .exe C-Sharp  >>
"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\modules\spi\generator"                                            << File .exe của Perl khi chạy   >>
"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\spi\workspace\E2xFCC1\4_2_2"                          << Chạy build test case hàng loạt >>
"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\common\modules\spi\test_cfg\plan"                                 << SỬa file gốc trong này Test_spec sẽ thay đổi theo >>
"D:\ws\01_Training Material\03_Csharp_GENTOOL\Assignment"                                                                      << Bài tập trong đây >>
"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\E2x\modules\spi\reqtify\E2xFCC1\Inputs\02_Design_Specification"   << File Parameter và Configuration >>
"D:\SVN_New\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\E2x\common_family\make\ghs"                                   << SampleApp.bat >>
"D:\SVN_New\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\modules\spi\sample_application\E2xFCC1\obj\ghs"               << Output Result >>

"D:\SVN_New\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\modules\spi\src"                                              << SPI_Lib >>
"D:\SVN_New\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\E2x\common_family\src\ghs"                                    << Interrupt_VectorTable.c >> 
"D:\SVN_New\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\modules\spi\sample_application\src"                           << App_SPI_Common_Sample.c >>
"D:\SVN_New\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\modules\spi\sample_application\E2xFCC1\src"                   << App_SPI_E2xFCC1_Sample.c >>
"D:\SVN_New\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\common\generic\stubs\4_2_2\Det\src"                           << Det.c >>
"D:\SVN_New\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\modules\spi\sample_application\E2xFCC1\4_2_2\config"          << Sửa CDF >>

"D:\SVN\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\internal\X2x\common\modules\fls\test_unit\app\src"                             << File c cho Unit Test bên FLS >>
"D:\SVN_New\01_MCALTraining\01_MCAL\09_mcal_e2x_dev\external\X2x\modules\fls"                                                  << File source code và header cho UT >>